python_django/django_level_four/learning_templates/basic_app/urls.py
from django.urls import path
from basic_app import views

#TEMPLATE_TAGGING
app_name = 'basic_app' # Django will look into this in templates, if relative url is used. This needs to match in the templates, {% url app_name:template_name%}

urlpatterns= [
    path('relative/',views.relative,name= 'relative'),
    path('other/',views.other,name='other')

]

python_django/django_level_four/learning_templates/learning_templates/urls.py
from django.contrib import admin
from django.urls import path, include
from basic_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index,name='index'),
    path('basic_app/',include('basic_app.urls'))
]

python_django/django_level_four/learning_templates/basic_app/models.py
from django.db import models

# Create your models here.

python_django/django_level_four/learning_templates/basic_app/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
    context_dict = {'text':'hello world','number':100}
    return render(request,'basic_app/index.html',context_dict)

def other(request):
    return render(request,'basic_app/other.html')

def relative(request):
    return render(request,'basic_app/relative_url_template.html')

python_django/django_level_four/learning_templates/templates/basic_app/base.html
<!DOCTYPE html>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>base html</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

</head>
<body>
    <nav class="navbar navbar-default navbar-static-top">
        <div class="container">
            <ul class="nav navbar-nav">
                <li><a class="navbar-brand" href="{%url 'index'%}">BRAND</a></li>
                <li><a class="navbar-link" href="{%url 'admin:index'%}">Admin</a></li>
                <li><a class="navbar-link" href="{%url 'basic_app:other'%}">Other</a></li>
            </ul>
        </div>
    </nav>
    <div class="container">
        {% block body_block %}
        <!-- Everything outside of the block will be inherited if you extend base in other templates.-->
        {%endblock%}

    </div>
    
</body>
</html>

python_django/django_level_four/learning_templates/templates/basic_app/index.html
<!DOCTYPE html>
{%extends "basic_app/base.html"%}
    {% block body_block %}
    <h1>Welcome to index!</h1>
    <h2>This is an example of template inheritance in index.html!</h2>
    <h1>{{text | upper}} </h1> <!--upper is a built-infilter, it capitalizes the text-->
    <h1>{{number | add:"99"}}</h1> <!-- add is a built-in filter, it adds 99 to number -->
    <h1>Demonstration of custom cut filter: {{text | cut:"hello"}}</h1> <!--cut is a custom filter, it cuts hello from text-->
    {% endblock %}

python_django/django_level_four/learning_templates/templates/basic_app/other.html
<!DOCTYPE html>
{%extends "basic_app/base.html"%}
    {% block body_block %}
    <h1>Welcome to the other page!</h1>
    <h2>This is an example of template inheritance!</h2>

    {% endblock %}

python_django/django_level_four/learning_templates/templates/basic_app/relative_url_template.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>relative_url_page</title>
  </head>
  <body>
    <h1>Welcome to relative_url_page! Template tagging is used here</h1>
    <a href="{% url 'basic_app:other' %}">The other page</a> <!--Needs to match app_name of urls.py in basic_app, Its not from the folder name, Its from app_name in urls.py-->
    <a href = "{%url 'admin:index' %}">Link to Admin</a>
    <a href = "{%url 'index' %}">Link to index</a>

  </body>
</html>